[package]
name = "cli"
version = "0.1.1"
authors = ["Daniel Rammer <hamersaw@bushpath.com>"]
edition = "2018"

[dependencies]
clap = {version = "2.33", features = ["yaml"]}
hdfs-comm = { path = "../../../hdfs-comm-rs" }
prost = "0.5"
shared = { path = "../shared" }
